### ISSUE TITLE
MySQL support would be nice

### ISSUE THREAD

**Issue by rwillmer** [Parbhat/cookiecutter-django-foundation#2]
Thanks for sharing this, very useful!

I'd like to use it with mysql rather than postgres. I've forked this to make the changes.

I'll do a PR for this if you want it. 

I've also asked @pydanny whether he wants to change his mind about having that choice upstream in https://github.com/pydanny/cookiecutter-django/issues/111

**Comment by Parbhat** [comment]
@rwillmer Thanks for trying this project. The purpose of this project is to give users of `cookiecutter-django` an option to use Zurb Foundation framework instead of Bootstrap. So, adding MySQL as an option will be out of scope. It would be great if you can create your fork and get it listed in `cookiecutter-django` Readme.
